BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS EnforcementAndComplianceAssuranceAuthority 
(
	EnforcementAndComplianceAssuranceAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL,
	DivisionAuthorityId INTEGER NOT NULL,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyEnforcementAndComplianceAssuranceAuthority FOREIGN KEY(PrcId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyEnforcementAndComplianceAssuranceAuthority PRIMARY KEY(EnforcementAndComplianceAssuranceAuthorityId)
);

CREATE TABLE IF NOT EXISTS EnforcementAndComplianceAssuranceObligations 
(
	EnforcementAndComplianceAssuranceObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyEnforcementAndComplianceAssuranceObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyEnforcementAndComplianceAssuranceObligations PRIMARY KEY(EnforcementAndComplianceAssuranceObligationId)
);

CREATE TABLE IF NOT EXISTS EnvironmentalJusticeAuthority 
(
	EnvironmentalJusticeAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyEnvironmentalJusticeAuthority FOREIGN KEY(PrcId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyEnvironmentalJusticeAuthority PRIMARY KEY(EnvironmentalJusticeAuthorityId)
);

CREATE TABLE IF NOT EXISTS EnvironmentalJusticeObligations 
(
	EnvironmentalJusticeObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyEnvironmentalJusticeObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyEnvironmentalJusticeObligations PRIMARY KEY(EnvironmentalJusticeObligationId)
);

CREATE TABLE IF NOT EXISTS ExternalAffairsAuthority 
(
	ExternalAffairsAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyExternalAffairsAuthority FOREIGN KEY(PrcId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyExternalAffairsAuthority PRIMARY KEY(ExternalAffairsAuthorityId)
);

CREATE TABLE IF NOT EXISTS ExternalAffairsObligations 
(
	ExternalAffairsObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyExternalAffairsObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyExternalAffairsObligations PRIMARY KEY(ExternalAffairsObligationId)
);

CREATE TABLE IF NOT EXISTS LaboratoryServicesAndAppliedSciencesAuthority 
(
	LaboratoryServicesAndAppliedSciencesAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyLaboratoryServicesAndAppliedSciencesAuthority FOREIGN KEY(DivisionAuthorityId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyLaboratoryServicesAndAppliedSciencesAuthority PRIMARY KEY(LaboratoryServicesAndAppliedSciencesAuthorityId)
);

CREATE TABLE IF NOT EXISTS LaboratoryServicesAndAppliedSciencesObligations 
(
	LaboratoryServicesAndAppliedSciencesObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeyLaboratoryServicesAndAppliedSciencesObligations PRIMARY KEY(LaboratoryServicesAndAppliedSciencesObligationId)
);

CREATE TABLE IF NOT EXISTS LandChemicalAndRevitalizationAuthority 
(
	LandChemicalAndRevitalizationAuthorityId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyLandChemicalAndRevitalizationDivisionAuthority FOREIGN KEY(DivisionAuthorityId) REFERENCES DivisionAuthority,
	CONSTRAINT PrimaryKeyLandChemicalAndRevitalizationAuthority PRIMARY KEY(LandChemicalAndRevitalizationAuthorityId)
);

CREATE TABLE IF NOT EXISTS LandChemicalAndRevitalizationObligations 
(
	LandChemicalAndRevitalizationObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeyLandChemicalAndRevitalizationObligations PRIMARY KEY(LandChemicalAndRevitalizationObligationId)
);

CREATE TABLE IF NOT EXISTS MissionSupportAuthority 
(
	MissionSupportAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT PrimaryKeyMissionSupportAuthority PRIMARY KEY(MissionSupportAuthorityId)
);

CREATE TABLE IF NOT EXISTS MissionSupportObligations 
(
	MissionSupportObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeyMissionSupportObligations PRIMARY KEY(MissionSupportObligationId)
);

CREATE TABLE IF NOT EXISTS OfficeOfRegionalCounselAuthority 
(
	OfficeOfRegionalCounselAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyOfficeOfRegionalCounselAuthority FOREIGN KEY(PrcId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyOfficeOfRegionalCounselAuthority PRIMARY KEY(OfficeOfRegionalCounselAuthorityId)
);

CREATE TABLE IF NOT EXISTS OfficeOfRegionalCounselObligations 
(
	OfficeOfRegionalCounselObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate datetime,
	LastActionDate datetime,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyOfficeOfTheRegionalAdministratorObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyOfficeOfRegionalCounselObligations PRIMARY KEY(OfficeOfRegionalCounselObligationId)
);

CREATE TABLE IF NOT EXISTS OfficeOfTheRegionalAdministratorAuthority 
(
	OfficeOfTheRegionalAdministratorAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT ForeignKeyOfficeOfTheRegionalAdministratorAuthority FOREIGN KEY(PrcId) REFERENCES Allocations,
	CONSTRAINT PrimaryKeyOfficeOfTheRegionalAdministratorAuthority PRIMARY KEY(OfficeOfTheRegionalAdministratorAuthorityId)
);

CREATE TABLE IF NOT EXISTS OfficeOfTheRegionalAdministratorObligations 
(
	OfficeOfTheRegionalAdministratorObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate datetime,
	LastActionDate datetime,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyOfficeOfTheRegionalAdministratorObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyOfficeOfTheRegionalAdministratorObligations PRIMARY KEY(OfficeOfTheRegionalAdministratorObligationId)
);

CREATE TABLE IF NOT EXISTS SuperfundAndEmergencyManagementAuthority 
(
	SuperfundAndEmergencyManagementAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT PrimaryKeySuperfundAndEmergencyManagementAuthority PRIMARY KEY(SuperfundAndEmergencyManagementAuthorityId)
);

CREATE TABLE IF NOT EXISTS SuperfundAndEmergencyManagementObligations 
(
	SuperfundAndEmergencyManagementObligationsId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate datetime,
	LastActionDate datetime,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeySuperfundAndEmergencyManagementObligations PRIMARY KEY(SuperfundAndEmergencyManagementObligationsId)
);

CREATE TABLE IF NOT EXISTS WaterDivisionAuthority 
(
	WaterDivisioinAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT PrimaryKeyWaterDivisionAuthority PRIMARY KEY(WaterDivisioinAuthorityId)
);

CREATE TABLE IF NOT EXISTS WaterDivisionObligations 
(
	WaterDivisionObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeyWaterDivisionObligations PRIMARY KEY(WaterDivisionObligationId)
);

CREATE TABLE IF NOT EXISTS WorkforceSupportAuthority 
(
	WorkforceSupportAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT PrimaryKeyWorkforceSupportAuthority PRIMARY KEY(WorkforceSupportAuthorityId)
);

CREATE TABLE IF NOT EXISTS WorkforceSupportObligations 
(
	WorkforceSupportAccountObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGERY NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT ForeignKeyWorkforceSupportAccountObligations FOREIGN KEY(PurchaseId) REFERENCES Purchases,
	CONSTRAINT PrimaryKeyWorkforceSupportObligations PRIMARY KEY(WorkforceSupportAccountObligationId)
);

CREATE TABLE IF NOT EXISTS WorkingCapitalFundAuthority 
(
	WorkingCaptialFundAuthorityId INTEGER NOT NULL UNIQUE,
	PrcId INTEGER NOT NULL UNIQUE,
	DivisionAuthorityId INTEGER NOT NULL UNIQUE,
	BudgetLevel TEXT(255),
	RPIO TEXT(255),
	BFY TEXT(255),
	FundCode TEXT(255),
	AhCode TEXT(255),
	OrgCode TEXT(255),
	AccountCode TEXT(255),
	RcCode TEXT(255),
	BocCode TEXT(255),
	Amount DOUBLE,
	FundName TEXT(255),
	BocName TEXT(255),
	Division TEXT(255),
	DivisionName TEXT(255),
	ActivityCode TEXT(255),
	NpmName TEXT(255),
	NpmCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	GoalCode TEXT(255),
	GoalName TEXT(255),
	ObjectiveCode TEXT(255),
	ObjectiveName TEXT(255),
	AllocationRatio DOUBLE,
	ChangeDate DATETIME,
	CONSTRAINT PrimaryKeyWorkingCaptialFundAuthority PRIMARY KEY(WorkingCaptialFundAuthorityId)
);

CREATE TABLE IF NOT EXISTS WorkingCapitalFundObligations 
(
	WorkingCapitalFundObligationId INTEGER NOT NULL UNIQUE,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255),
	BFY TEXT(255),
	RcCode TEXT(255),
	DivisionName TEXT(255),
	AhCode TEXT(255),
	AhName TEXT(255),
	FundCode TEXT(255),
	FundName TEXT(255),
	AccountCode TEXT(255),
	ActivityCode TEXT(255),
	BocCode TEXT(255),
	BocName TEXT(255),
	NpmCode TEXT(255),
	NpmName TEXT(255),
	OrgCode TEXT(255),
	ProgramProjectCode TEXT(255),
	ProgramProjectName TEXT(255),
	ProgramAreaCode TEXT(255),
	ProgramAreaName TEXT(255),
	DocumentControlNumbers TEXT(255),
	ReimbursableAgreementNumber TEXT(255),
	SiteProjectCode TEXT(255),
	DcnPrefix TEXT(255),
	DocType TEXT(255),
	FocCode TEXT(255),
	FocName TEXT(255),
	OriginalActionDate DATETIME,
	LastActionDate DATETIME,
	Commitments DOUBLE,
	OpenCommitments DOUBLE,
	Obligations DOUBLE,
	Deobligations DOUBLE,
	ULO DOUBLE,
	Expenditures DOUBLE,
	Used DOUBLE,
	CONSTRAINT PrimaryKeyWorkingCapitalFundObligations PRIMARY KEY(WorkingCapitalFundObligationId)
);

COMMIT;
