CREATE TABLE WaterDivisionObligations
(
	WaterDivisionObligationId INTEGER NOT NULL UNIQUE 
		CONSTRAINT PrimaryKeyWaterDivisionObligations PRIMARY KEY,
	PurchaseId INTEGER NOT NULL UNIQUE,
	RpioCode TEXT(255) NULL,
	BFY TEXT(255) NULL,
	RcCode TEXT(255) NULL,
	DivisionName TEXT(255) NULL,
	AhCode TEXT(255) NULL,
	AhName TEXT(255) NULL,
	FundCode TEXT(255) NULL,
	FundName TEXT(255) NULL,
	AccountCode TEXT(255) NULL,
	ActivityCode TEXT(255) NULL,
	BocCode TEXT(255) NULL,
	BocName TEXT(255) NULL,
	NpmCode TEXT(255) NULL,
	NpmName TEXT(255) NULL,
	OrgCode TEXT(255) NULL,
	ProgramProjectCode TEXT(255) NULL,
	ProgramProjectName TEXT(255) NULL,
	ProgramAreaCode TEXT(255) NULL,
	ProgramAreaName TEXT(255) NULL,
	DocumentControlNumbers TEXT(255) NULL,
	ReimbursableAgreementNumber TEXT(255) NULL,
	SiteProjectCode TEXT(255) NULL,
	DcnPrefix TEXT(255) NULL,
	DocType TEXT(255) NULL,
	FocCode TEXT(255) NULL,
	FocName TEXT(255) NULL,
	OriginalActionDate DATETIME NULL,
	LastActionDate DATETIME NULL,
	Commitments DOUBLE NULL,
	OpenCommitments DOUBLE NULL,
	Obligations DOUBLE NULL,
	Deobligations DOUBLE NULL,
	ULO DOUBLE NULL,
	Expenditures DOUBLE NULL,
	Used DOUBLE NULL
)